### PR TITLE
Added Jose (the sovereign state) to the project

### PR DESCRIPTION
**Pull request by zardilior**
I hope my change, is what you are looking for
I am really happy to help

### CODE REVIEW

**Comment by ozten** [comment]
Thank you for your support Jose!

The first line of the README "**Update: Closing signing for now**, since we need to work through the two blocker issues"

Although this repo is here for historical reference, the project is effectively dead. Of course if it became unblocked, I would revive your PR and merge. Thanks again.

**Comment by zardilior** [comment]
@ozten do let me know what I can do regarding those blockers

**Comment by ozten** [comment]
Please see Blocker Issues #8 and #23

**Comment by zardilior** [comment]
@ozten 

Ok, I've seen both of them

https://github.com/ozten/TLD.js/issues/23 - Seems like a political issue, which requires a political solution
https://github.com/ozten/TLD.js/issues/8 - Is way simpler but requires the above political solution

Are we interested in ideological solutions for these two blockers?

**Comment by zardilior** [comment]
I have a suggested 1st draft approach (I am really open to pivoting to other ideas):

According to:
https://en.wikipedia.org/wiki/Sovereign_state#:~:text=International%20law%20defines%20sovereign%20states,relations%20with%20other%20sovereign%20states.

For a country we require:
1- A permanent population
2- A defined territory
3- One gvt
4- The capacity to enter into relations with other sovereign states

My case:
My name is Jose and I am an anarchist, this is my culture but not my political stance on government. 
I would like to be recognized as a sovereign state, due to cultural discrepancies with every other country.

I claim to have:
1- A permanent population - Of 1 (me)
2- A defined territory - Of nothing (I can't have land, its against the culture)
3- One gvt - I am the absolute king of Jose, the king without land, which is an anarchist monarchy, 
nobody cares that I am its king
4- The capacity to enter into relations with other sovereign states - I can but don't want to

With this said, I ask the UN, and the ICANN to make my domain .js delegatable as it represents my countries name, jose, 
which is the only acceptable abbreviation of the name due to laws that have been passed by my gvt.

Also it would be a shame *wink, wink* if the js community, ignored that .js is owned by its landless king, and did whatever they wanted with it. A shame in the spirit of our culture.

**Comment by zardilior** [comment]
I hope you also laugh a bit @ozten, but for this we do need a political solution, which are hard to implement by small groups without ideological innovations.

**Pull request closed without merging**
